<a href="https://colab.research.google.com/github/shijithpulikkal/CodingFactory/blob/main/CF12%20Market%20Basket%20Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from itertools import combinations
from collections import Counter

In [2]:
from google.colab import drive
drive.mount('/content/drive')
df = pd.read_excel('/content/drive/My Drive/Colab Notebooks/Superstore.xlsx')
df.head()

Mounted at /content/drive

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,...,Postal_Code,Region,Product_ID,Category,Sub-Category,Product_Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [3]:
order_products = df.groupby('Order_ID')['Product_Name'].apply(lambda x: sorted(set(x)))
order_products

Order_ID
CA-2014-100006                                  [AT&T EL51110 DECT]
CA-2014-100090    [Hon 2111 Invitation Series Corner Table, Wils...
CA-2014-100293                                         [Xerox 1887]
CA-2014-100328    [Pressboard Covers with Storage Hooks, 9 1/2" ...
CA-2014-100363    [Binder Clips by OIC, Things To Do Today Spira...
                                        ...
US-2017-168802                                       [Binder Posts]
US-2017-169320    [Memorex 25GB 6X Branded Blu-Ray Recordable Di...
US-2017-169488    [Avoid Verbal Orders Carbonless Minifold Book,...
US-2017-169502    [Acco 6 Outlet Guardian Premium Plus Surge Sup...
US-2017-169551    [AmazonBasics 3-Button USB Wired Mouse, Apple ...
Name: Product_Name, Length: 5009, dtype: object

In [4]:
pair_counts = Counter()
for products in order_products:
  if len(products) > 1:
    for pair in combinations(products,2):
      pair_counts[pair] += 1

In [5]:
basket = pd.DataFrame(
    [(p[0],p[1],count) for p, count in pair_counts.items()],
    columns = ['ProductA', 'ProductB', 'TimesBoughtTogether']
)
basket

,ProductA,ProductB,TimesBoughtTogether
0,Hon 2111 Invitation Series Corner Table,"Wilson Jones Ledger-Size, Piano-Hinge Binder, ...",1
1,Binder Clips by OIC,Things To Do Today Spiral Book,1
2,Cameo Buff Policy Envelopes,DMI Arturo Collection Mission-style Design Woo...,1
3,Cameo Buff Policy Envelopes,Kensington Expert Mouse Optical USB Trackball ...,1
4,Cameo Buff Policy Envelopes,Prang Dustless Chalk Sticks,1
...,...,...,...
9886,O'Sullivan 3-Shelf Heavy-Duty Bookcases,Plastic Stacking Crates & Casters,1
9887,O'Sullivan 3-Shelf Heavy-Duty Bookcases,Xerox 216,1
9888,Plantronics CS510 - Over-the-Head monaural Wir...,Plastic Stacking Crates & Casters,1
9889,Plantronics CS510 - Over-the-Head monaural Wir...,Xerox 216,1
9890,Plastic Stacking Crates & Casters,Xerox 216,1

In [6]:
basket = basket[basket['TimesBoughtTogether'] > 1].sort_values(
    'TimesBoughtTogether', ascending=False

)
basket

,ProductA,ProductB,TimesBoughtTogether
366,Carina Double Wide Media Storage Towers in Nat...,GBC Wire Binding Combs,2
541,"Square Credit Card Reader, 4 1/2"" x 4 1/2"" x 1...",Staples,2
638,Avery 485,DMI Eclipse Executive Suite Bookcases,2
752,Acco D-Ring Binder w/DublLock,I Need's 3d Hello Kitty Hybrid Silicone Case C...,2
1049,Acme Value Line Scissors,Memorex Mini Travel Drive 64 GB USB 2.0 Flash ...,2
1095,Eldon Wave Desk Accessories,OIC Binder Clips,2
1169,"GBC Standard Recycled Report Covers, Clear Pla...",O'Sullivan 4-Shelf Bookcase in Odessa Pine,2
1216,GBC VeloBinder Manual Binding System,Insertable Tab Post Binder Dividers,2
1280,Newell 34,Staple envelope,2
1287,Staple envelope,Xerox 1971,2
1500,Cisco SPA508G,Global Commerce Series High-Back Swivel/Tilt C...,2
1794,Anker Astro Mini 3000mAh Ultra-Compact Portabl...,Bretford CR8500 Series Meeting Room Furniture,2
1926,Eldon Wave Desk Accessories,Poly Designer Cover & Back,2
2297,Cisco SPA301,"Seth Thomas 8 1/2"" Cubicle Clock",2
2691,GBC Recycled VeloBinder Covers,Wilson Jones Active Use Binders,2
2986,Logitech VX Revolution Cordless Laser Mouse fo...,Tennsco Industrial Shelving,2
3313,Avery Recycled Flexi-View Covers for Binding S...,Lumber Crayons,2
3411,X-Rack File for Hanging Folders,Xerox 192,2
3875,Hon Rectangular Conference Tables,Plantronics CS510 - Over-the-Head monaural Wir...,2
3892,Anker Astro 15000mAh USB Portable Charger,GBC Prestige Therm-A-Bind Covers,2
3998,Acco Perma 4000 Stacking Storage Drawers,Canon imageCLASS 2200 Advanced Copier,2
4103,Hon Olson Stacker Chairs,Staples,2
4498,Acco Hanging Data Binders,Newell 315,2
4595,GBC Plastic Binding Combs,Hon Valutask Swivel Chairs,2
4612,Avery 486,Logitech G35 7.1-Channel Surround Sound Headset,2
4705,"Wirebound Message Books, Four 2 3/4"" x 5"" Form...",Xerox 1882,2
4774,Advantus Rolling Storage Box,Great White Multi-Use Recycled Paper (20Lb. an...,2
4999,Anker 36W 4-Port USB Wall Charger Travel Power...,Staples,2
5162,Acco Hot Clips Clips to Go,Flat Face Poster Frame,2
5310,Boston 16765 Mini Stand Up Battery Pencil Shar...,Microsoft Natural Ergonomic Keyboard 4000,2
5452,"DAX Value U-Channel Document Frames, Easel Back",Recycled Easel Ring Binders,2
6478,Avery 505,"OIC #2 Pencils, Medium Soft",2
6758,KI Adjustable-Height Table,Staples,2
6816,Acco Side-Punched Conventional Columnar Pads,Avery Fluorescent Highlighter Four-Color Set,2
6821,Belkin Premiere Surge Master II 8-outlet surge...,SAFCO Optional Arm Kit for Workspace Cribbage ...,2
6940,KI Adjustable-Height Table,Toshiba IPT2010-SD IP Telephone,2
6951,Eldon Expressions Punched Metal & Wood Desk Ac...,GBC DocuBind TL300 Electric Binding System,2
8239,Hon 4700 Series Mobuis Mid-Back Task Chairs wi...,Staple envelope,2
8602,GBC Standard Therm-A-Bind Covers,Google Nexus 5,2
9208,Xerox 1894,Xerox 225,2