<a href="https://colab.research.google.com/github/shijithpulikkal/CodingFactory/blob/main/CF12%20Market%20Basket%20Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
from itertools import combinations
from collections import Counter

In [5]:
from google.colab import drive
drive.mount('/content/drive')
df = pd.read_excel('/content/drive/My Drive/Colab Notebooks/Superstore.xlsx')
df.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,...,Postal_Code,Region,Product_ID,Category,Sub-Category,Product_Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [8]:
order_products = df.groupby('Order_ID')['Product_Name'].apply(lambda x: sorted(set(x))).reset_index()
order_products

            Order_ID                                       Product_Name
0     CA-2014-100006                                [AT&T EL51110 DECT]
1     CA-2014-100090  [Hon 2111 Invitation Series Corner Table, Wils...
2     CA-2014-100293                                       [Xerox 1887]
3     CA-2014-100328  [Pressboard Covers with Storage Hooks, 9 1/2" ...
4     CA-2014-100363  [Binder Clips by OIC, Things To Do Today Spira...
...              ...                                                ...
5004  US-2017-168802                                     [Binder Posts]
5005  US-2017-169320  [Memorex 25GB 6X Branded Blu-Ray Recordable Di...
5006  US-2017-169488  [Avoid Verbal Orders Carbonless Minifold Book,...
5007  US-2017-169502  [Acco 6 Outlet Guardian Premium Plus Surge Sup...
5008  US-2017-169551  [AmazonBasics 3-Button USB Wired Mouse, Apple ...

[5009 rows x 2 columns]

In [10]:
pair_counts = Counter()
for products in order_products:
  if len(products) > 1:
    for pair in combinations(products,2):
      pair_counts[pair] += 1

In [12]:
basket = pd.DataFrame(
    [(p[0],p[1],count) for p, count in pair_counts.items()],
    columns = ['ProductA', 'ProductB', 'TimesBoughtTogether']
)
basket

   ProductA ProductB  TimesBoughtTogether
0         O        r                    2
1         O        d                    1
2         O        e                    1
3         O        _                    1
4         O        I                    1
..      ...      ...                  ...
80        N        m                    1
81        N        e                    1
82        a        m                    1
83        a        e                    1
84        m        e                    1

[85 rows x 3 columns]

In [13]:
basket = basket[basket['TimesBoughtTogether'] > 1].sort_values(
    'TimesBoughtTogether', ascending=False

)
basket

   ProductA ProductB  TimesBoughtTogether
9         r        _                    3
0         O        r                    2
6         r        d                    2
7         r        e                    2
10        r        I                    2
11        r        D                    2
12        d        e                    2
14        d        _                    2