<a href="https://colab.research.google.com/github/shijithpulikkal/CodingFactory/blob/main/CF15%20Cohort%20Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')
df = pd.read_excel('/content/drive/My Drive/Colab Notebooks/Superstore.xlsx')
df.head()

Mounted at /content/drive

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,...,Postal_Code,Region,Product_ID,Category,Sub-Category,Product_Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [3]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'])

In [5]:
first_purchase = df.groupby('Customer_ID')['Order_Date'].min().dt.to_period('M')
first_purchase.name = 'CohortMonth'
first_purchase

Customer_ID
AA-10315    2014-03
AA-10375    2014-04
AA-10480    2014-05
AA-10645    2014-06
AB-10015    2014-02
             ...
XP-21865    2014-01
YC-21895    2014-11
YS-21880    2015-01
ZC-21910    2014-10
ZD-21925    2014-08
Name: CohortMonth, Length: 793, dtype: period[M]

In [6]:
merged = df.merge(first_purchase, on ='Customer_ID')
merged['OrderMonth'] = merged['Order_Date'].dt.to_period('M')
merged.head()

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,...,Product_ID,Category,Sub-Category,Product_Name,Sales,Quantity,Discount,Profit,CohortMonth,OrderMonth
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,2015-10,2016-11
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,2015-10,2016-11
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,2016-06,2016-06
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,2015-10,2015-10
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,2015-10,2015-10

In [9]:
merged['MonthsSinceFirstPurchase'] = (
    (merged['OrderMonth']-merged['CohortMonth']).apply(lambda x: x.n)
    )
merged

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,...,Category,Sub-Category,Product_Name,Sales,Quantity,Discount,Profit,CohortMonth,OrderMonth,MonthsSinceFirstPurchase
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,2015-10,2016-11,13
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,2015-10,2016-11,13
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,2016-06,2016-06,0
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,2015-10,2015-10,0
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,2015-10,2015-10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,2014-01-21,2014-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028,2014-01,2014-01,0
9990,9991,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332,2014-03,2017-02,35
9991,9992,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932,2014-03,2017-02,35
9992,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200,2014-03,2017-02,35
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480,2014-09,2017-05,32

In [13]:
Cohort_summary = merged.groupby(['CohortMonth','MonthsSinceFirstPurchase']).agg(
    CohortRevenue=('Sales','sum'),
    ActiveCutomers=('Customer_ID','nunique')
).reset_index()

Cohort_summary

    CohortMonth  MonthsSinceFirstPurchase  CohortRevenue  ActiveCutomers
0       2014-01                         0      14236.895              32
1       2014-01                         1        225.232               3
2       2014-01                         3       1472.382               2
3       2014-01                         4         47.750               2
4       2014-01                         6        116.298               2
..          ...                       ...            ...             ...
889     2017-07                         0       1370.068               2
890     2017-07                         5        238.684               1
891     2017-09                         0       1038.260               1
892     2017-10                         0       1593.528               2
893     2017-11                         0       1205.584               1

[894 rows x 4 columns]

In [16]:
cohort_pivot = Cohort_summary.pivot(
    index='CohortMonth', columns='MonthsSinceFirstPurchase', values='CohortRevenue'
)

cohort_pivot

MonthsSinceFirstPurchase,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
CohortMonth,,,,,,,,,,,,,,,,,,,,,
2014-01,14236.8950,225.232,NaN,1472.3820,47.7500,NaN,116.298,907.584,1609.700,1477.6260,...,2788.5840,204.096,1576.309,1960.700,807.898,357.0800,8075.530,2051.569,12298.762,665.12
2014-02,4294.6600,634.310,596.252,576.2340,NaN,697.386,1040.400,11907.525,3345.146,6347.6400,...,560.6460,159.280,6447.905,782.616,1072.896,996.9020,1571.165,3605.562,604.534,NaN
2014-03,55056.6990,1519.546,2543.338,3298.7236,3101.2180,NaN,2860.124,1833.342,5968.528,2654.7920,...,4769.0484,5709.824,3162.986,3007.568,4786.222,2486.5112,8718.464,6102.418,NaN,NaN
2014-04,24707.1650,2410.624,875.455,2325.4680,454.1520,3195.573,1245.682,6778.990,4387.109,6.6800,...,2420.3280,5826.792,4147.648,6109.317,3210.674,4051.6612,7996.418,NaN,NaN,NaN
2014-05,18070.3410,1685.128,1862.666,653.2600,8717.3390,462.944,10024.595,7146.804,2463.350,748.5760,...,2512.4340,677.482,3327.961,5503.260,11595.319,2290.7400,NaN,NaN,NaN,NaN
2014-06,28735.8210,351.216,31.000,733.9520,104.1520,5489.491,3241.380,43.660,146.420,649.9720,...,285.3800,6760.413,1804.020,15355.630,3699.516,NaN,NaN,NaN,NaN,NaN
2014-07,25492.1410,2188.379,1044.661,NaN,1319.1340,4257.844,2759.794,NaN,4581.381,342.1820,...,2408.2820,7954.193,5918.620,5072.975,NaN,NaN,NaN,NaN,NaN,NaN
2014-08,22634.6935,8059.582,272.422,3807.4400,1244.3860,4411.208,2586.352,162.496,1060.226,401.5660,...,3803.0120,4280.287,8030.025,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-09,43648.8948,1882.084,3490.648,7160.2785,31.5380,188.862,2850.152,2138.150,5369.336,137.6600,...,4262.4210,4303.850,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-10,20829.9950,563.722,964.936,10.3680,1100.3030,5321.128,2316.614,1363.920,3382.266,2394.5460,...,3558.1670,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-11,31697.2587,5332.212,NaN,2563.3640,3601.7220,1278.314,131.244,1563.712,1607.372,3820.5120,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12,21599.5010,3130.160,218.350,1208.8880,1070.4840,897.356,1084.978,4144.415,1738.320,1576.6040,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01,3031.9876,NaN,16.776,NaN,1461.1395,937.608,586.560,NaN,NaN,551.1770,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-02,1882.9840,NaN,330.150,NaN,NaN,170.352,NaN,1113.355,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-03,12696.0686,485.784,570.492,2229.2630,860.9160,1203.441,999.734,30.840,1377.688,53.0880,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-04,3019.4600,NaN,NaN,231.9200,NaN,2.808,3107.774,119.952,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-05,5916.3900,NaN,NaN,64.7500,1281.2620,NaN,705.702,3554.090,405.344,111.1040,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-06,3250.0980,2048.856,310.364,4378.1300,299.9000,178.968,252.920,NaN,1127.976,2906.5830,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-07,4155.3190,NaN,NaN,869.5500,1370.4820,776.440,NaN,310.900,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-08,7417.2420,1293.754,139.424,3053.8660,302.6460,NaN,NaN,NaN,NaN,165.9760,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-09,5243.1480,77.880,1014.638,6.6880,1709.7380,121.830,1285.976,379.488,186.852,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-10,6533.0965,NaN,982.118,NaN,NaN,NaN,NaN,874.308,NaN,85.5000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-11,1688.0210,5.760,59.990,NaN,NaN,NaN,55.972,145.500,3943.446,179.5368,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-12,7468.8660,316.000,NaN,30.3360,114.0100,2144.030,NaN,874.886,37.264,124.9040,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-01,2855.2500,623.960,NaN,41.5680,NaN,23.616,20.936,94.080,NaN,24.7030,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-02,46.5440,NaN,88.040,NaN,NaN,NaN,NaN,NaN,1649.750,61.1200,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-03,1378.7780,NaN,5090.168,NaN,227.3040,NaN,143.240,235.152,143.330,413.0080,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-04,2839.4940,115.385,NaN,292.7960,121.0920,911.704,NaN,25.350,NaN,479.5740,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-05,12542.8230,NaN,3136.868,1625.2400,21.8800,100.496,2952.616,698.500,2166.390,287.3260,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-06,1812.2680,911.256,3888.897,434.0040,54.7920,1489.724,11.232,2113.567,NaN,81.6560,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-07,109.6300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.9880,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-08,1985.2140,NaN,NaN,NaN,NaN,1239.833,NaN,91.726,331.866,903.4220,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-10,98.1600,NaN,2003.520,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-11,584.8400,NaN,1370.535,NaN,296.0220,244.650,NaN,NaN,NaN,266.5200,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-12,2674.3300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-03,485.0500,NaN,NaN,6.3700,558.8100,210.008,NaN,674.872,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-04,16.7390,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-06,47.9760,NaN,NaN,NaN,NaN,NaN,65.856,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-07,1370.0680,NaN,NaN,NaN,NaN,238.684,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-09,1038.2600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-10,1593.5280,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11,1205.5840,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN