<a href="https://colab.research.google.com/github/shijithpulikkal/CodingFactory/blob/main/CF7%20Top%20N%20Products%20per%20Category.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
df = pd.read_excel('/content/drive/My Drive/Colab Notebooks/Superstore.xlsx')
df.head()

Mounted at /content/drive

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,...,Postal_Code,Region,Product_ID,Category,Sub-Category,Product_Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [ ]:
df2 = df.groupby(['Category','Product_Name'])['Sales'].sum().reset_index(name='Total_Sales')
df2.head()

    Category                        Product_Name  Total_Sales
0  Furniture    12-1/2 Diameter Round Wall Clock      551.448
1  Furniture            24-Hour Round Wall Clock      487.512
2  Furniture            36X48 HARDFLOOR CHAIRMAT      369.248
3  Furniture    3M Hangers With Command Adhesive      108.040
4  Furniture  3M Polarizing Light Filter Sleeves      216.340

In [ ]:
df2['Rank'] = (df2.groupby('Category')['Total_Sales'].rank(method = 'min', ascending = False))
df2

,Category,Product_Name,Total_Sales,Rank
0,Furniture,12-1/2 Diameter Round Wall Clock,551.448,226.0
1,Furniture,24-Hour Round Wall Clock,487.512,237.0
2,Furniture,36X48 HARDFLOOR CHAIRMAT,369.248,257.0
3,Furniture,3M Hangers With Command Adhesive,108.040,341.0
4,Furniture,3M Polarizing Light Filter Sleeves,216.340,286.0
...,...,...,...,...
1845,Technology,iKross Bluetooth Portable Keyboard + Cell Phon...,477.660,270.0
1846,Technology,iOttie HLCRIO102 Car Mount,215.892,345.0
1847,Technology,iOttie XL Car Mount,223.888,343.0
1848,Technology,invisibleSHIELD by ZAGG Smudge-Free Screen Pro...,442.554,283.0
1849,Technology,netTALK DUO VoIP Telephone Service,1112.788,184.0

In [ ]:
top3 = df2[df2['Rank'] <= 3].sort_values(['Category','Rank']).reset_index(drop=True)
top3

,Category,Product_Name,Total_Sales,Rank
0,Furniture,HON 5400 Series Task Chairs for Big and Tall,21870.5760,1.0
1,Furniture,"Riverside Palais Royal Lawyers Bookcase, Royal...",15610.9656,2.0
2,Furniture,Bretford Rectangular Conference Table Tops,12995.2915,3.0
3,Office Supplies,Fellowes PB500 Electric Punch Plastic Comb Bin...,27453.3840,1.0
4,Office Supplies,GBC DocuBind TL300 Electric Binding System,19823.4790,2.0
5,Office Supplies,GBC Ibimaster 500 Manual ProClick Binding System,19024.5000,3.0
6,Technology,Canon imageCLASS 2200 Advanced Copier,61599.8240,1.0
7,Technology,Cisco TelePresence System EX90 Videoconferenci...,22638.4800,2.0
8,Technology,Hewlett Packard LaserJet 3310 Copier,18839.6860,3.0

In [ ]:
df2[['Rank','Category', 'Product_Name']]

       Rank    Category                                       Product_Name
0     226.0   Furniture                   12-1/2 Diameter Round Wall Clock
1     237.0   Furniture                           24-Hour Round Wall Clock
2     257.0   Furniture                           36X48 HARDFLOOR CHAIRMAT
3     341.0   Furniture                   3M Hangers With Command Adhesive
4     286.0   Furniture                 3M Polarizing Light Filter Sleeves
...     ...         ...                                                ...
1845  270.0  Technology  iKross Bluetooth Portable Keyboard + Cell Phon...
1846  345.0  Technology                         iOttie HLCRIO102 Car Mount
1847  343.0  Technology                                iOttie XL Car Mount
1848  283.0  Technology  invisibleSHIELD by ZAGG Smudge-Free Screen Pro...
1849  184.0  Technology                 netTALK DUO VoIP Telephone Service

[1850 rows x 3 columns]